### ISSUE TITLE
Adapt Python program to use improved communication system 

### ISSUE THREAD

**Issue by kmrowiec** [abersailbot-archive/sailbot2013#1]
Communication between SailbotLogic and Python needs to be improved, to enable new functionality, like:
*sending waypoints over xbee
*sending obstacle position (avoiding moving obstacle of known position) 
*sending positions of other boats, either for collision avoidance or for swarm behaviour tasks

It will also make the system more robust and easier to expand. Description of the improved system can be found on the [wiki page](https://github.com/AberSailbot/sailbot2013/wiki/SailbotLogic---Python-Communication-Protocol)

**Comment by kragniz** [comment]
Done
